### ISSUE TITLE
Patch to use Nextion display with TJC

### ISSUE THREAD

**Issue by ghostolo90** [hagronnestad/tjc-usart-hmi-english-patch#2]
Hi,
i found a way to use TJC editor 0.55 with a Nextion display, and i upload succesfully a project with anti-aliased font.
Is it possible to add it to this patch? The method i used is similar, with your knowldege i think we can solve this problem.
if you are interested in, mail me to ghostolo90@gmail.com.

**Comment by hagronnestad** [comment]
@ghostolo90 Yes, I think I mentioned you on the Nextion Discord too. Get in touch with me here on the issue or in Discord. 😃

**Comment by BGERI95** [comment]
TJC has made some changes in the code and so the new v0.55 is not translatable with the patch. Is there any other way to translate it?

**Comment by ersinkecis** [comment]
> TJC has made some changes in the code and so the new v0.55 is not translatable with the patch. Is there any other way to translate it?

Yeah. The hmitype.dll file is no longer included in the package. I think they embedded this file in exe. language conversion is no longer possible. :(

**Comment by hagronnestad** [comment]
@ersinkecis Yes, as mentioned in the repo-description, this patch only works for a specific 0.55 release. And you're right, hmitype.dll is embedded in the exe. Come to the Unofficial Nextion User Forum Discord (https://discord.gg/z5EVyc) for more information.

**Comment by audiobrian** [comment]
https://github.com/audiobrian/usart_hmi_english_translation
