### ISSUE TITLE
Link for the 0.55 version which can be patched

### ISSUE THREAD

**Issue by hubshi** [hagronnestad/tjc-usart-hmi-english-patch#3]
Thanks for your patch for TJC editor , I am unable to find the editor with the HMI DLL files. I have downloaded the 0.55 version as per discussed in the forum. Can you please share the link  of the archived Editor which can be patched with your software.?

Best regards

**Comment by hagronnestad** [comment]
Are you on the Unofficial Nextion Discord? (https://discord.gg/xyvbDPV)

**Comment by hubshi** [comment]
Yes I am on Unofficial Nextion Discord.

**Comment by kjngmax** [comment]
I already download TJC HMI editor v0.55 and English patch file but when i run patch file has error. Please help me.


TJC USART HMI English Patch
*** Make sure to run me as administrator! ***

This program will try to locate and patch 'hmitype.dll'.
A backup of the original file will be created as 'hmitype.dll.original'.

Press any key to continue...

Trying to locate 'hmitype.dll'...

Could not find 'hmitype.dll', please run this program from the same folder as 'hmitype.dll' or paste the complete path now.

Path to hmitype.dll:

The file you entered doesn't exist. Exiting...

Press any key to exit...

**Comment by audiobrian** [comment]
https://github.com/audiobrian/usart_hmi_english_translation
