### ISSUE TITLE
Educational learning

### ISSUE THREAD

**Issue by MS-elug** [hagronnestad/tjc-usart-hmi-english-patch#4]
Hello, 
Interesting patch, I would like to learn how did you manage to find the right place in the binary for such update. If that's not too complex, would you teach us how you proceed ? I'm really interested :)

**Comment by hagronnestad** [comment]
It's quite limited what I can teach you by answering on a GitHub-issue. I'm not even any kind of professional at this topic, I just learn by doing. I would look up reverse engineering and go from there. Sorry for the short answer.
