### ISSUE TITLE
Way late to this party but Anycubic just started using TJC screens, looking for a source to download the TJC HMI editor v0.55 

### ISSUE THREAD

**Issue by TTVert** [hagronnestad/tjc-usart-hmi-english-patch#6]
I'm on the unofficial Nextion discord but haven't gotten any info yet.  Is there a way you can provide me a link w/o getting in trouble?  If not I undestand.

Thanks
Dave

**Comment by hagronnestad** [comment]
I'm not up to date regarding the current TJC/Nextion situation to be honest. Last time I checked the easiest way to develop for and flash TJC panels, is to develop in the Nextion HMI editor and then there should be a tool to convert either the project or the resulting TFT-file so that it can be flashed to a TJC panel.

**Comment by TTVert** [comment]
> I'm not up to date regarding the current TJC/Nextion situation to be honest. Last time I checked the easiest way to develop for and flash TJC panels, is to develop in the Nextion HMI editor and then there should be a tool to convert either the project or the resulting TFT-file so that it can be flashed to a TJC panel.

Unfortunately you cannot directly convert the Nextion created file to one that the TJC UART editor can use.  There are some checksum changes that need to be made, etc.  Not so cut and dried unfortunately.  It sucks though as TJC is going to likely be the screen  they move to more and it seems that all new Kobra series is using.  It's also the replacement screen AC is sending out now.

**Comment by hagronnestad** [comment]
Someone has made a converter that implements the needed checksum re-calculation etc. The Discord was my source last time I used it.

**Comment by TTVert** [comment]
> Someone has made a converter that implements the needed checksum re-calculation etc. The Discord was my source last time I used it.
Any idea who or what discord?  I had asked here but they made no mention of it when I asked how they were handling this.

![image](https://github.com/hagronnestad/tjc-usart-hmi-english-patch/assets/24374538/7e3b6489-aec0-4083-aab0-70e9d31556fd)

**Comment by hagronnestad** [comment]
It should be the correct Discord.
